//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncePence.Adapters
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Words = new HashSet<Word>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Describtion { get; set; }
    
        public virtual ICollection<Word> Words { get; set; }
    }
}
